### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MrRevillod** [goodbyepavlyi/Matebook-D15-2021-Hackintosh#3]
Can you tell me what I have to do to install hackintosh, I have the same model of matebook

**Comment by goodbyepavlyi** [comment]
Hello, you should follow this [guide](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/windows-install.html#downloading-macos) for downloading the macOS Recovery. Then, you can copy the EFI folder from this repository and the macOS Recovery you have created onto your USB stick. Feel free to contact me if you run into any problems.

**Comment by MrRevillod** [comment]
thx for your quick response, I'll follow the guide :)

**Comment by MrRevillod** [comment]
![imagen](https://user-images.githubusercontent.com/104238144/214133242-64435fd4-a2db-4a79-90ee-f5a8ac9bec61.png)

This is what my bootable usb should look like?

**Comment by MrRevillod** [comment]
i'm on linux

**Comment by goodbyepavlyi** [comment]
Should be just like that, give it a try.

**Comment by MrRevillod** [comment]
![imagen](https://user-images.githubusercontent.com/104238144/214139925-faead325-44e7-4655-bca9-b3f1317b7ea1.png)
If I applied your version of Efi, should I skip the part of the image or is it also necessary?

**Comment by goodbyepavlyi** [comment]
You have to only copy my EFI from this repository, only thing you have to download is the macOS Recovery.

**Comment by MrRevillod** [comment]
Last question lol,,,, my current system uses ext4 as file system, should I format the disk and change the file system manually or will the mac installer itself provide me with that option?

**Comment by goodbyepavlyi** [comment]
It will provide you with an option to delete the parition with the ext4 filesystem on it, but if you want to resize your ext4 parition, it won't be able to. You should use the APFS filesystem instead of the "macOS External Journaled" I have experienced many issues with that one such as not booting.

**Comment by MrRevillod** [comment]
i think something goes wrong idk windows logo?
![1AF058DD-6A58-4AAE-94B1-3270D2D73357](https://user-images.githubusercontent.com/104238144/214144279-3c5e58c1-41bb-4bdd-a7d9-113db5a53c17.jpeg)

**Comment by goodbyepavlyi** [comment]
Try to press Space or Shift, it should show up more options.

**Comment by MrRevillod** [comment]
lol, what should i choose?

![image](https://user-images.githubusercontent.com/104238144/214145767-095f527d-50cc-4649-b8f7-d22905a8f9ae.jpg)

**Comment by goodbyepavlyi** [comment]
That's weird it's not showing your macOS Recovery. Could you show me the contents of your "com.apple.recovery.boot" folder on the USB?

**Comment by MrRevillod** [comment]
contains BaseSystem.chunklist and BaseSystem.bmg

btw do u have discord? only for write and send imgs more fluently

**Comment by goodbyepavlyi** [comment]
Yep, I do. It's "goodbyepavlyi <3#7332"

**Comment by goodbyepavlyi** [comment]
Issue resolved by https://github.com/goodbyepavlyi/Matebook-D15-2020-Hackintosh/commit/c395bab8e25bef60db4d98d68b1911f653ceafe6 and https://github.com/goodbyepavlyi/Matebook-D15-2020-Hackintosh/commit/833ae489b549b15555a13fa5ef6d7fd356c675e0.

**Comment by cjames-cyber** [comment]
> Issue resolved by [c395bab](https://github.com/goodbyepavlyi/Matebook-D15-2020-Hackintosh/commit/c395bab8e25bef60db4d98d68b1911f653ceafe6) and [833ae48](https://github.com/goodbyepavlyi/Matebook-D15-2020-Hackintosh/commit/833ae489b549b15555a13fa5ef6d7fd356c675e0).

same issue here how do you fix the problem window logo only apear

**Comment by goodbyepavlyi** [comment]
> > Issue resolved by [c395bab](https://github.com/goodbyepavlyi/Matebook-D15-2020-Hackintosh/commit/c395bab8e25bef60db4d98d68b1911f653ceafe6) and [833ae48](https://github.com/goodbyepavlyi/Matebook-D15-2020-Hackintosh/commit/833ae489b549b15555a13fa5ef6d7fd356c675e0).
> 
> 
> 
> same issue here how do you fix the problem window logo only apear 

Did you download the macOS Recovery to the USB Drive?

**Comment by RitikMulani** [comment]
hey i also got a different issue for this? can you help me
