### ISSUE TITLE
Picker menu invisible

### ISSUE THREAD

**Issue by lastant** [goodbyepavlyi/Matebook-D15-2021-Hackintosh#7]
I managed to install Ventura on 2021 model not with this EFI (for some reason it didn't work), but a similar one: https://drive.google.com/drive/folders/1a8fsRA2xmWBJwkcOIP0_tg_vv_Q15bmt But when trying to dual boot with Windows and pressing Esc on startup, there is nothing shown except for Huawei logo. However, if I press right arrow key and then Enter, it will boot into MacOS, without pressing Esc it boots into Windows. So it seems the Picker menu is simply invisible, although working. It's strange that during installation the menu did work. 
Do you see the picker menu?

**Comment by goodbyepavlyi** [comment]
This issue isn't related to this repository. The EFI you have provided is for a later model and doesn't match the 2020 one.
