### ISSUE TITLE
Not working audio!!!

### ISSUE THREAD

**Issue by Trexium2** [goodbyepavlyi/Matebook-D15-2021-Hackintosh#8]
Hello!
I installed macOS Monterey on Huawei Matebook D15 2020 on i5 10210U (fortunately, everything worked perfectly with your EFI), but the sound does not work. AIDA64 shows the intel Comet Point-LP PCH audio codec - cAVS (Audio, Voice, Speech) PCI. I tried all the methods, but none worked. Can you tell me what the problem is and how to solve it?

**Comment by goodbyepavlyi** [comment]
Audio is not supported due to the laptop using an unsupported audio chipset Everest ES8316 since the drivers are not made for macOS there's no solution to solving it.

**Comment by Trexium2** [comment]
and it turns out that for a laptop you need to buy an external sound card?

**Comment by goodbyepavlyi** [comment]
If you would like to have sound then you do

**Comment by Trexium2** [comment]
OK, thanks for answer!
