### ISSUE TITLE
Not working bluetooth!

### ISSUE THREAD

**Issue by Trexium2** [goodbyepavlyi/Matebook-D15-2021-Hackintosh#9]
Bluetooth doesn't work!

**Comment by Trexium2** [comment]
![Снимок экрана 2023-10-29 в 12 56 09](https://github.com/goodbyepavlyi/Matebook-D15-2020-Hackintosh/assets/50524961/f5e100ca-4eb7-475c-bab5-e9c048a7cd27)
ok, now I can’t get bluetooth on my Hackintosh, although it works on Windows. I installed all the kexts, but bluetooth is not displayed in hackintool. How to deal with this?

**Comment by goodbyepavlyi** [comment]
Bluetooth should show up in PCIe since it’s not connected via USB.

**Comment by Trexium2** [comment]
![B9D71496-D4B5-4AD8-ADD6-8C2CAC884FB4](https://github.com/goodbyepavlyi/Matebook-D15-2020-Hackintosh/assets/50524961/f7f3a8f5-2ddb-4adc-9df4-8d785347c4db)

**Comment by goodbyepavlyi** [comment]
Can you run some kind of Live OS of Linux and run this command `lspci -knn; lsusb`? It will respond with all the PCI devices and USB devices.

**Comment by goodbyepavlyi** [comment]
Closing the issue due to no response

**Comment by Trexium2** [comment]
Sorry for not answering on time.
Can you reopen the issue so I can send you pictures?

**Comment by Trexium2** [comment]
![20231118_180032](https://github.com/goodbyepavlyi/Matebook-D15-2020-Hackintosh/assets/50524961/28665bd4-e112-4143-bf09-02ef8ba7c2e0)
![20231118_180036](https://github.com/goodbyepavlyi/Matebook-D15-2020-Hackintosh/assets/50524961/476180f5-83bc-4160-a00a-2e5bf8eb2785)
something like this happened

**Comment by goodbyepavlyi** [comment]
Could you try installing this [kext](https://openintelwireless.github.io/IntelBluetoothFirmware/Installation.html) into your EFI?

**Comment by Trexium2** [comment]
Tried it, doesn't work. 
It simply doesn’t start, even though I wrote it in config.plist

**Comment by goodbyepavlyi** [comment]
In that case I'm out of options since your model of laptop is also different that could be the reason.

**Comment by Trexium2** [comment]
Probably, but it's a shame that it didn't work.
I'll have to use an external usb bluetooth 
But, thank you for your help!
